version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "master"
    open-pull-requests-limit: 20
    groups:
      xunit:
        patterns:
          - xunit*
      nuget:
        NuGet:
          patterns:
           - NuGet.*
        System.IO.Abstractions:
          patterns:
           - System.IO.Abstractions*

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
