name: Test

on: [pull_request]

jobs:
  # build-warnings:
  #   name: Build warnings check
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 30
  #   steps:
  #     - uses: actions/checkout@v1
  
  #     - name: Build
  #       run: dotnet build /WarnAsError

  test:
    name: Tests for .net core ${{ matrix.framework }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        framework: ['2.1', '3.1']
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v1

    - name: Smoke test
      run: dotnet run --framework netcoreapp${{ matrix.framework }} --project src/DotNetOutdated

    - name: Tests
      run: dotnet test --framework netcoreapp${{ matrix.framework }}
