name: Test

on: [pull_request, workflow_dispatch]

env:
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: 1
  FORCE_COLOR: 3
  TERM: xterm

jobs:
  # build-warnings:
  #   name: Build warnings check
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 30
  #   steps:
  #     - uses: actions/checkout@v4.2.2

  #     - name: Build
  #       run: dotnet build /WarnAsError

  test:
    name: Tests for framework ${{ matrix.framework }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        framework: ['net8.0', 'net9.0']
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4.2.2

    - name: Setup .NET
      uses: actions/setup-dotnet@v5.0.0
      with:
        dotnet-version: | 
            8.0.x
            9.0.x

    - name: Smoke test
      run: |
        dotnet run --configuration Release --framework ${{ matrix.framework }} --project src/DotNetOutdated test-projects/development-dependencies

    - name: Tests
      run: dotnet test --configuration Release --framework ${{ matrix.framework }}
