name: Test

on: [pull_request, workflow_dispatch]

jobs:
  # build-warnings:
  #   name: Build warnings check
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 30
  #   steps:
  #     - uses: actions/checkout@v2.3.4
  
  #     - name: Build
  #       run: dotnet build /WarnAsError

  test:
    name: Tests for framework ${{ matrix.framework }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        framework: ['netcoreapp2.1', 'netcoreapp3.1', 'net5.0']
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v2.3.4

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1.8.1
      with:
        dotnet-version: '2.1.x'

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1.8.1
      with:
        dotnet-version: '3.1.x'

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1.8.1
      with:
        dotnet-version: '5.0.x'

    - name: Smoke test
      run: |
        dotnet run --framework ${{ matrix.framework }} --project src/DotNetOutdated test-projects/development-dependencies

    - name: Tests
      run: dotnet test --framework ${{ matrix.framework }}
