name: Test

on: [pull_request, workflow_dispatch]

jobs:
  # build-warnings:
  #   name: Build warnings check
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 30
  #   steps:
  #     - uses: actions/checkout@v3.1.0

  #     - name: Build
  #       run: dotnet build /WarnAsError

  test:
    name: Tests for framework ${{ matrix.framework }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        framework: ['net6.0', 'net7.0']
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v3.1.0

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3.0.2
      with:
        dotnet-version: '6.0.x'

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3.0.2
      with:
        dotnet-version: '7.0.x'

    - name: Smoke test
      run: |
        dotnet run --framework ${{ matrix.framework }} --project src/DotNetOutdated test-projects/development-dependencies

    - name: Tests
      run: dotnet test --framework ${{ matrix.framework }}
